### ISSUE TITLE
Issue when default empty string

### ISSUE THREAD

**Issue by AhmedElywa** [notiz-dev/prisma-dbml-generator#1]
if you have a string field has a default attribute with an empty string you get issue

```prisma
title     String   @default("")
```
convert to

```
  title String [not null, default: ]
```

you need to make it 

```
  title String [not null, default: ""]
```

**Comment by AhmedElywa** [comment]
Also if has value like 

```prisma
color              String                 @default("blue")
```

consvert to 

```
  color String [not null, default: blue] must be "blue"
```

**Comment by marcjulian** [comment]
Thanks for reporting. I will fix it as asap

**Comment by marcjulian** [comment]
@AhmedElywa please try with the new version [0.2.3](https://github.com/notiz-dev/prisma-dbml-generator/releases/tag/v0.2.3) and let me know if it works for you.
