### ISSUE TITLE
Single quotes in comments should be escaped

### ISSUE THREAD

**Issue by iddan** [notiz-dev/prisma-dbml-generator#13]
Having a comment with a single quote (`'`) should be escaped (`\'`) to prevent a syntax error.
```prisma
model Foo {
    /// foo's bar
    bar String
}
```
Will generate broken text.

**Comment by marcjulian** [comment]
@iddan thanks for reporting. Please test out the latest dev release with the fix

```bash
npm install -D prisma-dbml-generator@0.6.0-dev.2
```

**Comment by iddan** [comment]
It works!
