### ISSUE TITLE
Update @prisma/sdk to a newer version

### ISSUE THREAD

**Issue by RichardMEN11** [notiz-dev/prisma-dbml-generator#20]
The version of @prisma/sdk which is currently used has outdated and vulnerable dependencie (tar) which caused `npm audit` to warn me. 

Maybe it would be useful to update @prisma/sdk  to 3.0.2 - if possible. 

Thanks a lot for your awesome work 🌟

**Comment by marcjulian** [comment]
@RichardMEN11 I have update @prisma/sdk and released it in the new [0.8.0](https://github.com/notiz-dev/prisma-dbml-generator/releases/tag/v0.8.0) release.

**Comment by RichardMEN11** [comment]
Thanks a lot! 👍🏼  @marcjulian
