### ISSUE TITLE
List of strings support

### ISSUE THREAD

**Issue by PabloSzx** [notiz-dev/prisma-dbml-generator#29]
Is there any specific reason this library converts `String[]` to `String`? I'm guessing that this also would happen for a list of `Int` or any other primitive

![image](https://user-images.githubusercontent.com/8672915/145740998-f24c4a16-7eb8-4ff7-ba14-d5697a0dcd4c.png)

**Comment by marcjulian** [comment]
@PabloSzx thanks for pointing this out. There is no specific reason that it is not supported yet, just that for testing it I used sqlite as adapter and thus does not support primitive list. 

Will need to check DBML api how to add primitive list. Do you know how this looks like in the DBML format?
Happy to accept a PR for this feature if you like!

**Comment by marcjulian** [comment]
I checked in dbdiagram.io and the following syntax seems to work fine

```
Table Group {
  keywords String[]
}
```

**Comment by PabloSzx** [comment]
@marcjulian I found an issue, just doing `field.isList ? ...` It also adds the [] to many-to-many & one-to-many relations, which technically are also lists in practice

![image](https://user-images.githubusercontent.com/8672915/147152403-e52331b3-d739-46e4-8356-97a7a1ff9c4c.png)

**Comment by PabloSzx** [comment]
created #29, checking for `field.isList && !field.relationName` seemed to be enough :+1:

**Comment by marcjulian** [comment]
@PabloSzx test it out with this dev release https://github.com/notiz-dev/prisma-dbml-generator/releases/tag/v0.9.0-dev.0
