### ISSUE TITLE
`prisma` intalled global = `Error: spawn prisma-dbml-generator ENOENT`

### ISSUE THREAD

**Issue by ludufre** [notiz-dev/prisma-dbml-generator#44]
Hi.

If I run `prisma generate` I get error, but not with `npx prisma generate` :

```bash
Error: spawn prisma-dbml-generator ENOENT
```

Windows 11
Node 18.14.1

**Comment by marcjulian** [comment]
Hi @ludufre, I cannot test this error as I am only using Mac.
