### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by areindl** [notiz-dev/prisma-dbml-generator#45]
First of all: Thank you! This is a wonderful little library and I really appreciate using it.

Unfortunately, installing it brings a lot of dependency issues:

![image](https://user-images.githubusercontent.com/5536491/233129304-338019cf-a6a9-4402-8785-f256e605184d.png)

Any plan to upgrade the deps?

Best
Anton

**Comment by marcjulian** [comment]
Awesome you like this generator. Are you able to provide a PR?

**Comment by ArthurSegato** [comment]
Hello and good evening!

I made a PR to address **one of the four** vulnerabilities identified by npm, as soon as I have more time I'll try to fix the rest.

would you be so kind as to analyse the PR?

**Comment by marcjulian** [comment]
Please try out the latest dev release with update dependencies and security issues fixed.

```
npm install -D prisma-dbml-generator@0.11.0-dev.0
```

**Comment by kuaj** [comment]
Looks and works nicely, thank you for the update! 💚

**Comment by rgrzesk** [comment]
When can we expect the release to happen? :)

**Comment by marcjulian** [comment]
Sorry for the delay. I published following new versions with updated deps:

- [0.11.0](https://github.com/notiz-dev/prisma-dbml-generator/releases/tag/v0.11.0) with Prisma 4.13.0
- [0.11.1](https://github.com/notiz-dev/prisma-dbml-generator/releases/tag/v0.11.1) with Prisma 4.16.1 and deps update
- [0.12.0](https://github.com/notiz-dev/prisma-dbml-generator/releases/tag/v0.12.0) with Prisma 5.0.0

Updating Prisma to latest version results in additional changes to the dmmf, which I don't have time right now to address. If anyone like to create PR for it, I will review it.
