### ISSUE TITLE
Update to `2.15.0`

### ISSUE THREAD

**Issue by timsuchanek** [notiz-dev/prisma-dbml-generator#6]
In `2.15.0`, which is being released today, we have a breaking change:
All types, which are not a model, an enum or `PrismaClient` can't be directly imported from `@prisma/client` anymore, but need to be imported from a new namespace called `Prisma`.
Example:

#### Before
```ts
import { JsonValue, PrismaClient } from '@prisma/client'
```

#### After
```ts
import { Prisma, PrismaClient } from '@prisma/client'

Prisma.JsonValue
```

You can already try this out now with the latest `dev` version of Prisma Client: `@prisma/client@dev`.

This change has been introduced in `2.12.0`, but now we actually remove the old exports. So you should probably require your users to have at least `@prisma/client@2.12.0`.

A link to our failing e2e test with `prisma-dbml-generator`: https://github.com/prisma/e2e-tests/runs/1733749649?check_suite_focus=true

**Comment by timsuchanek** [comment]
It turned out, it was something different in our tests, this package continues to work just fine with `2.15.0`, no changes required.

**Comment by marcjulian** [comment]
@timsuchanek do I need to still require the user to have at least `@prisma/client@2.12.0`?
